### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by TheRealLenon** [Tekoding/KoIdentity#1]
## Description
an end user has the ability to create an account on the platform depending on the applicable configuration or implementation. An Account may only exist once.

## Proces
1. Submit the **RegistrationDTO**
2. Check, if the provided **RegistrationDTO** is valid
3. Check if the user already exist
4. Create the user from the provided **RegistrationDTO**
5. Save the user in the database
6. Create the **RegistrationResult** and return

## Failes when
1. The provided data transfer object is not correct
2. The user already exist in the database
3. The creation from the data transfer object failed
4. The insert of the user into the database failed

## Tasks
- [x] Create a registration data transfer object
- [x] Create a user model
- [x] Create the registration process
- [x] Create unit tests
- [ ] Create xml documentation
