### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by TheRealLenon** [Tekoding/KoIdentity#2]
## Description
After successful registration of an user account on the platform, the end user is allowed to log in to the platform.

## Process
1. Provide **LoginDTO**
2. Check, if the provided **LoginDTO** is valid
3. Check if the user already exist
4. Check if the provided password is correct
5. Create a login token
6. Assign the login token to the user
7. Save the login into the database
8. Return the login token

## Failes when
1. The provided data transfer object is not correct
2. The user does not exist
3.The provided password is not correct
4. The creation of the token failed
5. The assignment of the token to the user failed
6. The Creation into the database failed

## Tasks
- [ ] Create a login data transfer object
- [ ] Create a model for logins
- [ ] Create the login process
- [ ] Create unit tests
- [ ] Create xml documentation
