### ISSUE TITLE
Account Deletion

### ISSUE THREAD

**Issue by TheRealLenon** [Tekoding/KoIdentity#3]
## Description
In case of the need to leave the platform permanently, a user has the right to remove his account from the platform completely and without exception.

## Process
1. Provide the user id of the account going to be deleted
2. Check if the user id is valid
3. Check if the user exist
4. Delete the user

## Failes when
1. The user id is not valid
2. The user does not exist

## Tasks
- [ ] Remove the user from the database
- [ ] Create unit tests
- [ ] Create xml documentation
