### ISSUE TITLE
Role System

### ISSUE THREAD

**Issue by TheRealLenon** [Tekoding/KoIdentity#4]
## Description
To ensure an end user can only access areas to which he or she is authorized or to excecute user interactions to which he or she is acutally authorized, a role or rights system that is as generic as possible is required.

## Tasks
- [ ] Assign a user a role
- [ ] Remove a role from a user
- [ ] Create a area only accessible for loggedin users
- [ ] Create a area only accessible for administrators
