### ISSUE TITLE
Passwort Reset

### ISSUE THREAD

**Issue by TheRealLenon** [Tekoding/KoIdentity#5]
# Description
If an already existing user account is no longer accessible (e.g.: in case of a forgotten password), it is possible to reset the password.

The prerequisite for resetting the password is the prior creation of a "password reset" request. This generates a verification code that validates the subsequent reset. It can be defined in the implementation settings whether a new password is generated and assigned automatically, or whether the user can assign his new password independently.

To reset the password, optional parameters can be specified depending on the configuration or the respective implementation, which are required for a successful reset. At least, however, the verification code is required.

## Process
- Create password reset request
- Based on the current configuration generate a new password or let the user create a new password
- Hash the new password and save it in the database

## Failes when
- No user provided
- No verification code provided
- User does not exist
- Verification code does not exist

## Tasks
- [ ] Create abstraction for password reset request
- [ ] Create default implementation for password reset request
- [ ] Create abstraction for password change
- [ ] Create default implementation for password change
